// 预设主题颜色
export const themePresets = {
  default: {
    primary: '#00B894',
    secondary: '#00CEC9',
    accent: '#4A90E2',
    success: '#2ECC71',
    warning: '#F1C40F',
    error: '#E74C3C',
    info: '#3498DB',
    'primary-darken-1': '#00957B',
    'secondary-darken-1': '#00A8A8',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'on-accent': '#FFFFFF',
    'on-success': '#FFFFFF',
    'on-warning': '#000000',
    'on-error': '#FFFFFF',
    'on-info': '#FFFFFF',
    'theme-background': '#E8F5F3',
    'theme-surface': '#F2FAF8',
    'theme-hover': '#D1EBE7'
  },
  blue: {
    primary: '#1976D2',
    secondary: '#2196F3',
    accent: '#82B1FF',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#FF5252',
    info: '#2196F3',
    'primary-darken-1': '#1565C0',
    'secondary-darken-1': '#1E88E5',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'on-accent': '#000000',
    'on-success': '#FFFFFF',
    'on-warning': '#000000',
    'on-error': '#FFFFFF',
    'on-info': '#FFFFFF',
    'theme-background': '#EEF4FB',
    'theme-surface': '#F5F9FD',
    'theme-hover': '#E0EAF5'
  },
  green: {
    primary: '#2ECC71',
    secondary: '#27AE60',
    accent: '#A8E6CF',
    success: '#27AE60',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#3498DB',
    'primary-darken-1': '#27AE60',
    'secondary-darken-1': '#219A52',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'on-accent': '#000000',
    'on-success': '#FFFFFF',
    'on-warning': '#000000',
    'on-error': '#FFFFFF',
    'on-info': '#FFFFFF',
    'theme-background': '#EFF8F1',
    'theme-surface': '#F6FBF7',
    'theme-hover': '#E1F0E4'
  },
  purple: {
    primary: '#9C27B0',
    secondary: '#BA68C8',
    accent: '#E1BEE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#FF5252',
    info: '#2196F3',
    'primary-darken-1': '#8E24AA',
    'secondary-darken-1': '#AB47BC',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'on-accent': '#000000',
    'on-success': '#FFFFFF',
    'on-warning': '#000000',
    'on-error': '#FFFFFF',
    'on-info': '#FFFFFF',
    'theme-background': '#F6EFF8',
    'theme-surface': '#FAF5FC',
    'theme-hover': '#EFE0F4'
  },
  orange: {
    primary: '#F39C12',
    secondary: '#E67E22',
    accent: '#FFB74D',
    success: '#2ECC71',
    warning: '#F1C40F',
    error: '#E74C3C',
    info: '#3498DB',
    'primary-darken-1': '#D68910',
    'secondary-darken-1': '#CA6F1E',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'on-accent': '#000000',
    'on-success': '#FFFFFF',
    'on-warning': '#000000',
    'on-error': '#FFFFFF',
    'on-info': '#FFFFFF',
    'theme-background': '#FDF4E8',
    'theme-surface': '#FEF9F2',
    'theme-hover': '#FAEBD7'
  }
}

// 获取主题配置
export const getThemeConfig = (themeName = 'default') => {
  const colors = themePresets[themeName] || themePresets.default
  
  return {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        colors: {
          ...colors,
          background: colors['theme-background'],
          surface: colors['theme-surface'],
          'surface-variant': colors['theme-hover'],
          'on-surface-variant': '#424242',
          'grey-lighten-5': colors['theme-background'],
          'grey-lighten-4': colors['theme-surface'],
          'grey-lighten-3': colors['theme-hover'],
          'grey-lighten-2': '#E0E0E0',
          'grey-lighten-1': '#BDBDBD',
          'grey-darken-1': '#757575',
          'grey-darken-2': '#616161',
          'grey-darken-3': '#424242',
          'grey-darken-4': '#212121',
        },
      },
      dark: {
        dark: true,
        colors: {
          ...colors,
          background: '#121212',
          surface: '#1E1E1E',
          'surface-variant': '#2D2D2D',
          'on-surface-variant': '#EEEEEE',
          'grey-lighten-5': '#2D2D2D',
          'grey-lighten-4': '#363636',
          'grey-lighten-3': '#404040',
          'grey-lighten-2': '#494949',
          'grey-lighten-1': '#525252',
          'grey-darken-1': '#757575',
          'grey-darken-2': '#616161',
          'grey-darken-3': '#424242',
          'grey-darken-4': '#212121',
        },
      },
    },
  }
} 